name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install dependencies
        run: yarn install

      - name: Generate changelog file
        uses: rhysd/changelog-from-release/action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/healthicons-flutter/CHANGELOG.md
          commit: false
          args: -d=false

      - name: Build
        run: yarn run build

      - name: Prepare packages
        run: yarn run prepublish-all
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Commit release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release Version ${{ github.ref_name }} [skip ci]
          branch: main
          push_options: --force

      - name: Update tag
        run: |
          git -c user.email="actions@github.com" -c user.name="GitHub Actions" tag -fa ${{ github.ref_name }} -m "${{ github.ref_name }}"
          git push -f origin ${{ github.ref_name }}

      - name: Set .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish React package
        run: |
          yarn --cwd ./packages/healthicons-react install 
          yarn --cwd ./packages/healthicons-react publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Publish React Native package
        run: |
          yarn --cwd ./packages/healthicons-react-native install
          yarn --cwd ./packages/healthicons-react-native publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Publish Vue package
        run: |
          yarn --cwd ./packages/healthicons-vue install
          yarn --cwd ./packages/healthicons-vue publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Publish Flutter
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          relativePath: ./packages/healthicons-flutter
